### ISSUE TITLE
请问如何禁止无限滑动？

### ISSUE THREAD

**Issue by ghost** [waylife/InfiniteViewPager#11]
看了一下源代码..没太看懂实现思路
请问如何设置滑动到最后一个后禁止再右滑回到第一个。
谢谢。

**Comment by waylife** [comment]
暂时无法阻止，如果需要建议自行实现。

我们知道ViewPager滑动到最左边以及最右边是无法继续滑动的。那怎么去实现无限滑动，这里用的方案就是在一屏数据的两边分别增加一屏数据，滑动的时候在中间滑动，滑动到边界时会在onPageSelected自动调整位置到中间。
比如你有1 2 3三个数据，但是给adapter的数目是InfiniteViewPager.FakePositionHelper.MULTIPLIER*3（一般InfiniteViewPager.FakePositionHelper.MULTIPLIER>=3）
最终index以及数据如下
0  1   2   3   4   5   6   7   8
1  2   3   1   2   3   1   2   3
实际实用的位置为345，滑动到2时会调整到5，滑动到6时会调整到3.
