### ISSUE TITLE
Circle Indicator issue  

### ISSUE THREAD

**Issue by amit016verma** [waylife/InfiniteViewPager#14]
I am using infinite ViewPager inside the fragment that point of time its working fine but the issue come when I am replacing with  the another fragment and come back then getting number of circular line indicator became double number (like If first time showing 3 dots after replacing fragment and comeback getting 6 dots of circle) (This issue cumming with both indicator)

**Comment by amit016verma** [comment]
can you resolve this bugs

**Comment by waylife** [comment]
Could you paste your code here, it's not likely caused by this library.

**Comment by amit016verma** [comment]
Thanks for replying , I solved the issue, there was problems with my code
sorry for that
